language: android
sudo: required
jdk: oraclejdk8
branches: master
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
deploy:
   provider: releases
   file: lilhut-debug.apk
   on:
     repo: ogunoz/littlehut-android
     tags: true
     jdk: oraclejdk8
